import 'chat.dart';

class CallLog {
  final String date, callStatus, name;
  final String image, duration, size;
  final bool isVideoCall;
  final Chat chat;

  CallLog({
    this.name = '',
    this.image = '',
    this.date = '',
    this.callStatus = '',
    this.isVideoCall = false,
    required this.chat,
    this.duration = '',
    this.size = '',
  });
}

List callsData = [
  CallLog(
    name: "John Wilson",
    image: "assets/images/user1.jpg",
    date: 'Today, 12:19 am',
    callStatus: 'Incoming',
    isVideoCall: false,
    chat: chatsData[0],
    duration: '01:23',
    size: '104 kB',
  ),
  CallLog(
    name: "Amy Howard",
    image: "assets/images/user4.jpg",
    date: 'Yesterday, 11:45 pm',
    callStatus: 'Incoming',
    isVideoCall: true,
    chat: chatsData[1],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "Edward Ray",
    image: "assets/images/user2.jpg",
    date: 'Yesterday, 11:57 pm',
    callStatus: 'Outgoing',
    isVideoCall: false,
    chat: chatsData[2],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "Jacob Jones",
    image: "assets/images/user3.jpg",
    date: '14 July, 9:19 am',
    callStatus: 'Incoming',
    isVideoCall: false,
    chat: chatsData[3],
    duration: '03:13',
    size: '410 kB',
  ),
  CallLog(
    name: "Albert Flores",
    image: "assets/images/user5.jpg",
    date: '13 July, 11:19 pm',
    callStatus: 'Incoming',
    isVideoCall: true,
    chat: chatsData[4],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "John Wilson",
    image: "assets/images/user1.jpg",
    date: '13 July, 11:50 pm',
    callStatus: 'Outgoing',
    isVideoCall: false,
    chat: chatsData[0],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "Amy Howard",
    image: "assets/images/user4.jpg",
    date: '11 July, 10:19 am',
    callStatus: 'Incoming',
    isVideoCall: true,
    chat: chatsData[1],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "Edward Ray",
    image: "assets/images/user2.jpg",
    date: '10 July, 1:19 pm',
    callStatus: 'Outgoing',
    isVideoCall: false,
    chat: chatsData[2],
    duration: '02:19',
    size: '140 kB',
  ),
  CallLog(
    name: "Jacob Jones",
    image: "assets/images/user3.jpg",
    date: '09 July, 01:19 am',
    callStatus: 'Incoming',
    isVideoCall: false,
    chat: chatsData[3],
    duration: '01:43',
    size: '123 kB',
  ),
  CallLog(
    name: "Albert Flores",
    image: "assets/images/user5.jpg",
    date: '08 July, 02:19 pm',
    callStatus: 'Incoming',
    isVideoCall: true,
    chat: chatsData[4],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "John Wilson",
    image: "assets/images/user1.jpg",
    date: '03 July, 11:50 am',
    callStatus: 'Outgoing',
    isVideoCall: false,
    chat: chatsData[0],
    duration: '0:43',
    size: '82 kB',
  ),
  CallLog(
    name: "Amy Howard",
    image: "assets/images/user4.jpg",
    date: '01 July, 10:19 am',
    callStatus: 'Incoming',
    isVideoCall: true,
    chat: chatsData[1],
    duration: 'Unavailable',
    size: '',
  ),
  CallLog(
    name: "Edward Ray",
    image: "assets/images/user2.jpg",
    date: '01 July, 09:19 am',
    callStatus: 'Outgoing',
    isVideoCall: false,
    chat: chatsData[2],
    duration: '0:51',
    size: '94 kB',
  ),
];
